### ISSUE TITLE
FS Deportes not working 

### ISSUE THREAD

**Issue by tifoji** [emilsvennesson/kodi-fsgo#2]
Thanks for getting this going btw. Great job

FS Deportes is subbed and shows up in app but not in the addon.

**Comment by emilsvennesson** [comment]
Thanks for the report!

I'm aware of the schedule and will work on adding it soon (hopefully this weekend).

Regarding FS Deportes: I was under the impression that the API when signed in would list everything you have access to. Can you actually play content from FS Deportes using the app? It's not part of my subscription so I can't try it myself.

**Comment by tifoji** [comment]
Yes I am able to play FSD. It has the following calls in the log

`GET http://hlslinear-l3c.med1.foxsportsgo.com/ls02/foxsports/FOX_DEPORTES/live/2016/10/07/12575205/5000K/282/16/36/07_508.ts HTTP/1.1
Accept: */*
User-Agent: AppleCoreMedia/1.0 ( iPad; compatible; 3ivx HLS Engine/3.0.0.479; UWP.Desktop; x64; 264P AACP AC3P AESD CLCP HTPC HTPI HTSI MP3P MTKA HLSM )
Accept-Language: en-US
Accept-Encoding: gzip, deflate
Host: hlslinear-l3c.med1.foxsportsgo.com
Connection: Keep-Alive
Cookie: utag_main=v_id:0155e1d0aa19002231bcc1e81f6400096006708e00bd0$_sn:1$_ss:0$_pn:2%3Bexp-session$_st:1468374editedNE`

**Comment by tifoji** [comment]
This the epg i think

`GET https://media-api.foxsportsgo.com/epg/ws/live/all HTTP/1.1
Accept-Encoding: gzip, deflate
deportes: true
Cache-Control: no-cache, no-store, must-revalidate
Authorization: edited
If-Modified-Since: Mon, 27 Mar 1972 00:00:00 GMT
Host: media-api.foxsportsgo.com
Connection: Keep-Alive
Cookie: utag_main=v_id:edited
`

**Comment by emilsvennesson** [comment]
@siuside When browsing that EPG link from the web, are you able to see the FS Deportes events? Because that's the API page the add-on is using.

**Comment by tifoji** [comment]
I am capturing this via fiddler. There is one more interesting URL
`https://media-api.foxsportsgo.com/epg/ws/channel/all HTTP/1.1`

Yes both of these show the FSD events just fine (not via browser but fiddler with proper authorization and cookies in header)

**Comment by tifoji** [comment]
Sample output from channel/all

`
{"header":{"request":"/channel/all","error":null,"status":"OK","time_stamp":"2016-10-08T16:51:34.280Z","request_id":null},"body":{"items":[{"type":"channel","id":29129,"title":"FOX","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":49070,"title":"FOX Sports 1","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":36770,"title":"FOX Sports 2","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":32652,"title":"FS Southwest","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":32729,"title":"FOX Deportes","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":35287,"title":"FCS","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":50132,"title":"FSGO Extras","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false},{"type":"channel","id":50130,"title":"Big East Digital","airings":[],"urls":[],"device_disabled":false,"is_bonus_feed_roll_up":false}],"total_results":8,"results":null}}`

**Comment by emilsvennesson** [comment]
Could you post your response from https://media-api.foxsportsgo.com/epg/ws/live/all?

**Comment by emilsvennesson** [comment]
Could you please post a log from the add-on when logging in and browsing to Live? Don't forget to enable logging in both Kodi as well as the add-on settings.

**Comment by tifoji** [comment]
Here is the response from live/all
http://pastebin.com/ edited no longer required

**Comment by emilsvennesson** [comment]
@siuside Did you see my last comment? It'd be nice to get comparisons from the add-on as well. I'd also like to see what kind of response you get from the logging in.

**Comment by tifoji** [comment]
Yup I was in the middle of doing it. Here we go 

http://pastebin.com/edited no longer required

**Comment by tifoji** [comment]
So I do see the entitlements getting recognized correctly `"entitlements":["fs1","foxdep","fbc-fox","fss","fs2","fcs"`

but also see tls/ssl error but not sure if it the one impacting and even if so why would it only impact fxdep?

`13:35:12 T:1496   ERROR: C:\Users\htpc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
13:35:12 T:1496   ERROR: C:\Users\htpc\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning`

**Comment by tifoji** [comment]
Here is a live/all from just a couple of mins ago in official app/fiddler to do a compare vs the addon

http://pastebin.com/edited no longer required

I do see FXDEP in the official app

**Comment by emilsvennesson** [comment]
@siuside: Thanks for the log. Don't worry about the SSL error; it's just a warning that's not really an issue. 

So I can see that you're definitely entitled to watch Deportes. Are you seeing all the other programs from the app except for Deportes? I can see that there's an option in the app for enabling/disabling Deportes programs, so maybe I'm missing some needed parameters in the schedule request.

**Comment by tifoji** [comment]
Yes I am seeing all other programs. If you look at the bottom of the results, clearly only FXDEP is missing in the json results

Kodi addon: "total_results":8
App: "total_results":9

**Comment by emilsvennesson** [comment]
Could you please send me a full Fiddler session from the app? There might be some params sent in the schedule request that we need.

**Comment by tifoji** [comment]
Yup I was just going to post, I found the required option in the header. Would be nice to add this as a preference in option

GET /epg/ws/live/all HTTP/1.1
Accept-Encoding: gzip, deflate
**deportes: true**
Cache-Control: no-cache, no-store, must-revalidate
Authorization: Edited
If-Modified-Since: Mon, 27 Mar 1972 00:00:00 GMT
Host: media-api.foxsportsgo.com
Connection: Keep-Alive
Cookie: utag_main=v_id:Edited

**Comment by emilsvennesson** [comment]
@siuside Great! Thanks a lot. This should be fixed with 6b50a5083593d94f629e200f4ee254593ce4f2a9.

**Comment by tifoji** [comment]
That didn't take very long :)

Tested and confirmed issue is fixed. We can close this one. Thanks again for the great work

**Comment by emilsvennesson** [comment]
@siuside Thanks again for the help. :)
