### ISSUE TITLE
Fox Sports Go Logo Submission

### ISSUE THREAD

**Issue by MonkeyWrench32** [emilsvennesson/kodi-fsgo#7]
Thank you so much for creating this add-on! To express my gratitude I made a Fox Sports Go icon for the app that follows the official icon guidelines and has the correct shade of blue for the background. Enjoy!

![fox_sports_go](https://cloud.githubusercontent.com/assets/11048283/23885851/997def98-084c-11e7-88cd-18e3ffffe8bb.png)

**Comment by emilsvennesson** [comment]
Thanks for your submission and I'm glad you're enjoying the add-on! :)

I have actually decided to not use the official icon as that would imply that this would be an official app from Fox. While the current icon is similar, it's still distinguishable and doesn't use the official Fox logo.

**Comment by MonkeyWrench32** [comment]
I totally understand. No worries and thanks again!
