### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by ralyodio** [emilsvennesson/kodi-fsgo#8]
This appears to no longer work since switching to https://www.foxsoccermatchpass.com

**Comment by emilsvennesson** [comment]
It sure would have been nice if you could be a bit more specific... what exactly is not working? It works just fine here. I'm not sure what that service has to do with Fox Sports Go to be honest.

**Comment by ralyodio** [comment]
Sorry I thought this was for the soccer2go. Do you know of a kodi addon which works with foxsoccermatchpass.com?

**Comment by emilsvennesson** [comment]
I doubt there is one available. I am closing this seeing as it is unrelated to Fox Sports Go.
